name: Node Nginx CI
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: 'Create env file'
        run: |
          touch .env
          echo NODE_ENV=production >> .env
          echo DO_MONGO_URI_LOCAL=${{ secrets.DO_MONGO_URI_LOCAL }} >> .env
          cat .env
      - name: install modules
        run: npm install
      - name: restart all apps
        run: pm2 restart all
        # run: cd frontend
        # run: npm install
        # run: sudo service nginx restart
      # - name: build project
      #   run: npm run build
      # - name: unit test
      #   run: npm run test:unit
      # - name: e2e test
      #   run: npm run test:e2e
      # - name: lint code
      #   run: npm run lint
